### ISSUE TITLE
DP error handling is broken

### ISSUE THREAD

**Issue by tomba** [t-c-collab/linux#12]
The DP and PHY drivers don't manage errors very well.
- mhdp_probe leaves resources enabled/allocated on error cases
- calls don't check the returned error value. e.g. mhdp's phy_configure calls are never checked. PHY's cdns_dp_phy_run returns void, even if it can fail.

**Comment by jsarha** [comment]
I think this issue has been fixed by now. @tomba , what do you say?

**Comment by jsarha** [comment]
This issue has been fixed since https://github.com/t-c-collab/linux/pull/42 and https://github.com/t-c-collab/linux/pull/36 were merged.
