### ISSUE TITLE
Push latest mhdp firmware to upstream

### ISSUE THREAD

**Issue by tomba** [t-c-collab/linux#16]
Push latest mhdp firmware to upstream

**Comment by sjakhadecdns** [comment]
Latest firmware (v2.0.0) for Cadence MHDP8546 DP bridge is now upstreamed.
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?h=master&id=b78a66c909c7150601e1b2a810b0e7c8f98d920c
