### ISSUE TITLE
Update PCIe + QSGMII config for correct PLL1 clock

### ISSUE THREAD

**Issue by kishon** [t-c-collab/linux#51]
For PCIe + QSGMII configuration where QSGMII was using PLL1 and was
expecting 10GHz clock, configuration was giving 8GHz clock. Update
register sequences to get correct PLL1 configuration.

**Comment by milindcdns** [comment]
Is this issue same as reported in "Update 46456784 PCIe link up failure in 1 lane or 2 lane modes when unused lanes are not assigned to PCIe Controller [10G Multi-Protocol PHY] "

**Comment by milindcdns** [comment]
This patch is streamed and merged. This issue can be closed.
