### ISSUE TITLE
Let's not update master constantly

### ISSUE THREAD

**Issue by tomba** [t-c-collab/linux#6]
@nmenon 
 
Syncing master to Linus' master via cron causes lots of needless updates and notifications, and at least I don't see any reason for it. In fact, I don't know why we even need to track Linus' master at all.

Lets only push when there's a reason to push. Then the activity reports actually tell something.

**Comment by nmenon** [comment]
Reason for tracking master is to make sure we have the latest code and changes are tracking to that. there are multiple teams trying to work and contribute up to upstream. while I agree there are notifications generated, but we can reduce the frequency to once a day, perhaps?

**Comment by tomba** [comment]
Yes, maybe once a day will reduce the activity reports enough.

But I still don't understand how it's useful to have master that tracks Linus' master. Can you explain how you see it used? It is for purely tracking upstream, not for merging our own branches in this repo, right?

**Comment by nmenon** [comment]
@tomba I reduced it to once a day (8pm CST)
# m h  dom mon dow 
00      20      * *     1,2,3,4,5,6,7

cronjob maintains the master including keeping all the rc and main tags updated - some folks do use a single tree and master ideally should reflect the current torvalds master.
