### ISSUE TITLE
Link training problem

### ISSUE THREAD

**Issue by tomba** [t-c-collab/linux#9]
Sometimes (I think only the first training after boot), I get

[   55.174467] cdns-mhdp a000000.dp-bridge: CR: max swing reached

and bad picture. I think the driver gets the link up, but with less than 4 lanes, and then the BW is not enough for the picture. That issue should be solved by the "filter videomodes according to BW" work.

But I think there are problems with the link training, as my cable and my monitor should be fine, and there should be no problems in getting a full link up.

**Comment by nmenon** [comment]
@milindcdns please assign?

**Comment by tomba** [comment]
This seems to happen only on a single monitor (although the monitor works ok with PC), so lets close.
